<?php



/*----------------------------------------------------------------------------------------------------------

  LOAD THE MAIN THEME FUNCTION FILES - WARNING: PLEASE DO NOT EDIT THIS FILE IN ANY WAY!

-----------------------------------------------------------------------------------------------------------*/


// If this file is called directly, busted!

if( !defined( 'ABSPATH' ) ) {

  exit;

}

add_action('after_setup_theme', 'remove_admin_bar');

function remove_admin_bar() {
	if ( !current_user_can('administrator') && !current_user_can('editor') && !current_user_can('contributor')) {
		show_admin_bar(false);
	}
}



$template_directory = get_template_directory();



// Basic theme functionality

require $template_directory . '/includes/functions.php';



// Theme Initialization

require $template_directory . '/includes/funtions-init.php';



// Theme hooks through Gameleon own functions.

require $template_directory . '/includes/tha-theme-hooks.php';



// Theme hooks

require $template_directory . '/includes/hooks.php';



// Post custom meta

require $template_directory . '/includes/post-custom-meta.php';



// Post Views Counter

require $template_directory . '/includes/post-views-count.php';



// Breadcrumb functions

require $template_directory . '/includes/functions-breadcrumb.php';



// Theme Widgets

require $template_directory . '/includes/widgets.php';



// Register sidebar widgets

require $template_directory . '/includes/functions-sidebar.php';



// MyArcadePlugin Api

require $template_directory . '/includes/myarcadeplugin_api.php';



// Responsive Adsense Ads

require $template_directory . '/includes/td-ads.php';



// Theme version

require $template_directory . '/includes/version.php';

function display_excerpt_properly($excerpt){
    return preg_replace('/Rip Red/', '', $excerpt);
}
